# Generated by Django 4.2.21 on 2025-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20250531_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='source',
            name='text_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
