# Generated by Django 4.2.21 on 2025-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
